### ISSUE TITLE
distinction between 802.1D and 802.1Q

### ISSUE THREAD

**Issue by gorryfair** [uoaerg/draft-tsvwg-dscp-considerations#91]
- S5.1.1: I've read this several times and I am still unclear about the distinction between 802.1D and 802.1Q. The first paragraph says zero is best effort and 1 is background. But then the second paragraph implies that 802.1D is somehow different because PCP1 is lower priority than PCP0.
- 
It is also ambiguous to me whether 1D and/or 1Q are just taking the top 3 bits of the DSCP or not. It might be better to clearly specify what 1D did, and then when 1Q did.

**Comment by gorryfair** [comment]
Do we understand the problem, apart from confusion?

It might be worth adding a historical note, since all these terms are in use:
(IEEE 802.1Q was revised in 2005 from the original recommendations in IEEE 802.1D-2004 and inputs from IEEE P802.1p.)

**Comment by ana-cc** [comment]
--we edited that section based on the following input from Sebastian:

I have one note though:

"5.1.  Mapping Specified for IEEE 802.11


   << This section is currently seeking more input. >>

   A 3-bit Priority Code Point (PCP) is specified in the IEEE 802.1Q tag
   to mark Ethernet frames to one of eight priority values.  The value
   zero indicates the default best effort treatment, and the value one
   indicates a background traffic class.  The remaining values indicate
   increasing priority.  Internet control traffic can be marked as six,
   and network control is marked as seven."

First, maybe reference IEEE Std 802.1Q-2018 Annex-I here as that discusses PCPs and their relationship to diffserv/intserv?


Then, there are still devices out in the field that do not treat PCP1 below PCP0 (for example some low port-count consumer switches). And given that older IEEE standards mapped PCP2, but not PCP1 lower than PCP0, it is to be expected that  there will be different behaviour depending on the age of deployed devices, especially since cheap consumer routers will likely never see a firmware update after they are sold, but might still linger on in the field for some time.

Best Regards
Sebastian

**Comment by ana-cc** [comment]
moved some of the text around in this commit - let me know if it reads any better:

https://github.com/uoaerg/draft-tsvwg-dscp-considerations/pull/94/commits/8ec5893046fbfe3b2e6498904b63951fc4d9721d

**Comment by gorryfair** [comment]
At last, I think now resolved in the PR - please review

**Comment by gorryfair** [comment]
Resolved in -10
